Адаптивная графика для всех страниц
htmlacademy-adaptive/1853291-pink-25 pull request #10
Opened 2022-05-16 22:06 UTC by zazuzai

хотела сделать проверку npm run lint, но получила такое в ответ
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db

нужно следовать этой рекомендации?

2022-05-16 22:42 UTC, zazuzai commented
> хотела сделать проверку npm run lint, но получила такое в ответ Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db
> 
> нужно следовать этой рекомендации?

И ещё не поняла про фавиконки:(
где мне взять ico? переименовать png в другой формат или как? 
пока что подключила svg как на первом курсе, правда просто написала type="img/svg" а не type="image/svg+xml"
и не поняла, надо ли мне создавать файл manifest.webmanifest с инструкцией для других иконок

2022-05-17 21:52 UTC, wrgraff requested changes

2022-05-17 21:52 UTC, wrgraff commented on source/sass/blocks/download-app.scss
> +    @media (min-resolution: 2dppx) {
С того момента, как добавляешь ретиновую картинку, использовать `background-size: auto` становится опасно.
Браузер если что не знает, что картинка ему выдана двойной плотности. И использует ее так же, как обычную. То есть, она станет огромной ))

Примерно вот такой:
![Скриншот сделанный 2022-05-18 в 00 33 46](https://user-images.githubusercontent.com/37917037/168913810-53700c9a-f26a-4d8d-ba7a-ef9db0ac8494.png)

2022-05-17 21:52 UTC, wrgraff commented on source/sass/blocks/product-features.scss
> +    background-image: url("../img/product-features/make-friends@2x.png");
Проблема с картинкой двойной плотности преследует и здесь (как в этой картинке, которая для списка, так и в других вариантах):
![Скриншот сделанный 2022-05-18 в 00 35 53](https://user-images.githubusercontent.com/37917037/168914086-469a5c11-b5f0-4e9e-9b5a-0ee3bd612cf7.png)

Проверь сайт через инспектор, он умеет имитировать двойную (и всякую прочую) плотность.
Включи ее и пройдись по всему сайту. Если что-то не так с картинками — это сложно будет не заметить =)

2022-05-17 21:52 UTC, wrgraff commented on source/catalog.html
>        <nav class="header__nav header__nav--closed">
Мы потеряли строку `<meta name="viewport" content="width=device-width, initial-scale=1">` на страницах формы и каталога.

Надо добавить, а то мобильная версия даже не включается.

https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/efc1d5ed83695192aa42920824559994f903f94b/source/catalog.html#L3-L7
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/efc1d5ed83695192aa42920824559994f903f94b/source/form.html#L3-L7

2022-05-17 21:52 UTC, wrgraff commented on source/index.html
> +    <link rel="apple-touch-icon" type="img/png" sizes="152x152" href="../img/favicons/favicon152.png">
Эти иконки нужно и на внутренние страницы добавить

https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/efc1d5ed83695192aa42920824559994f903f94b/source/catalog.html#L3-L7
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/efc1d5ed83695192aa42920824559994f903f94b/source/form.html#L3-L7

2022-05-17 21:52 UTC, wrgraff commented on source/index.html
> +    <link rel="apple-touch-icon" type="img/png" sizes="152x152" href="../img/favicons/favicon152.png">
А почему такой адрес? Папка `img` лежит на одном уровне с html-файлами. А у тебя будто уровнем выше получается

2022-05-17 21:52 UTC, wrgraff commented on source/catalog.html
> +            </picture>
А разве этой картинке не требуется разное кадрирование?
Как минимум там совсем разная высота изображений

2022-05-17 21:52 UTC, wrgraff commented on source/catalog.html
> +              <img class="photo-card__img" src="../img/catalog/photo-card/photo-1-mobile@1x.jpg" srcset="../img/catalog/photo-card/photo-1-mobile@2x.jpg 2x" alt="В центре кадра камера на штативе, на
Какой-то баг у тебя случился с путями к изображениям вдруг. Папка картинок ведь на одном уровне с html-файлами.
Да, локально у тебя все это работает, потому что "выход" из папки наверх не срабатывает. Потому что сервер запущен из `source` и он не видит ничего выше. Поэтому браузер не может выйти выше и ищет папку `img` в корне. И находит.

А вот ГитХаб, который публикует версию (ты в интерфейсе кнопочку жмешь такую для публикации) хостит твои страницы иначе, он располагает файлы вовсе не в корне. Обрати внимание на адрес ссылки:
https://htmlacademy-adaptive.github.io/1853291-pink-25/10/catalog.html
Ну и на то, что картинки там не отображаются тоже посмотри =)

2022-05-17 21:55 UTC, wrgraff commented
> хотела сделать проверку npm run lint, но получила такое в ответ
> Browserslist: caniuse-lite is outdated. Please run:
> npx browserslist@latest --update-db
> 
> нужно следовать этой рекомендации?

Проверка все равно работает (попробуй ерунду какую-нибудь написать и запустить). Конфигурация линтера — задача сложноватая для студента второго курса Академии, поэтому оставь как есть

2022-05-17 21:58 UTC, wrgraff commented
> где мне взять ico? переименовать png в другой формат или как?

Это так не сработает. Чтобы создать формат ico можно найти какой-нибудь онлайн-генератор формата ico. Их довольно много, гугли и бери тот, что покажется симпатичнее.

> пока что подключила svg как на первом курсе, правда просто написала type="img/svg" а не type="image/svg+xml"

На самом деле не уверен, что будут требовать именно ico, и если повторить подход с первого уровня, то он будет даже как-то поактуальнее.

> и не поняла, надо ли мне создавать файл manifest.webmanifest с инструкцией для других иконок

Здесь такого требования нет. Первый уровень верстки недавно сильно переписали и он посвежее.
Если есть силы и желание — добавь, это хорошая практика

2022-05-19 13:11 UTC, wrgraff approved these changes

2022-05-19 13:11 UTC, merged