Разметка главной страницы
htmlacademy-adaptive/1853291-pink-25 pull request #3
Opened 2022-04-02 18:43 UTC by zazuzai

2022-04-02 22:12 UTC, wrgraff requested changes
Про много комментариев я предупреждал! Не пугайся =)

Вообще, все хорошо: есть всего одна неувязочка с применением БЭМа, и то выглядит как некоторая перестраховка. При чем, формально это не будет ошибкой прям вот прямой, но по сути это не очень правильно. Когда с БЭМом всего одна проблема, да еще и такая — я считаю, что это успех =)

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            <li class="slider-pagination__item pagination__item--current"></li>
Тут по БЭМ ошибка фактическая. Модификатор `pagination__item--current` предполагает элемент `pagination__item`, а у тебя он `slider-pagination__item`

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +        <div class="price-table__pagination pagination">
Тут ошибка по БЭМу. `price-table__pagination` — элемент блока `price-table`.
Да, такой блок есть, конечно, но только это таблица, а наш `<div>` находится не в ней.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +      <h1 class="visually-hidden">Пинк - мобильное приложение для раскрашивания серых будней в розовый цвет.</h1>
Я бы все же `<h1>` рекомендовал помещать в `<main>`.
Не то чтобы это ошибка или прям плохо — заголовок первого уровня такой особенный, что может быть где угодно, но все же как-то логичнее, когда он не в неизменной верхней части сайта (в хэдере), а в основном контенте, который он как бы и озаглавливает.
Тем более, он у нас скрытый тут, нам ничего не стоит его перенести.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +          <span class="visually-hidden">Открыть меню.</span>
Тут кстати нет критерия про точку. Но если уж продолжать ему следовать, то надо везде: там про описания всех картинок так же работает, а вот в лого у тебя точки нет:
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L10-L12

Ну или просто забей =)

> Я кстати проверял скринридером — никакой разницы не почувствовал, что с точкой, что без. По крайней мере, на Маке через VoiceOver. Может, это не везде так.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +        <div class="header-nav__wrapper site-nav">
А вот ты прям на 100% уверена, что тебе эта обертка будет нужна? Я вот не уверен, что вокруг списка, который сам по себе обертка, нужна еще обертка.
Возможно, она понадобится для списка с логотипом (чтобы центрировать там), но это будет зависеть от кучи всего, так что и ее я бы заранее не добавлял.

Вообще, базовая рекомендация такая: во время разметки мы добавляем только те теги, которые вот прям точно понадобятся. Потому что добавить что-то всегда можно, а заметить, что обертка лишняя и убрать — это можно и забыть.

Есть еще вариант, если ты в каждой секции делаешь обертку всего контента, то можно прям вот систематично эти обертки сразу и проставить.
Но так как я вижу, что они расставлены скорее ситуативно, это тоже пока что не наш вариант )

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +      <a class="header__logo logo" href="#">
Ну, вообще у нас есть главная страница и на нее можно и нужно поставить ссылку.
Если ты не будешь делать "ссылку на саму себя", то нужно убрать совсем `href`. А если будешь, то надо прописать адрес. Заглушка тут точно не подходит.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +        <a class="copyright__link" href="https://htmlacademy.ru"></a>
По [ТЗ 3.8](https://up.htmlacademy.ru/adaptive/25/project/pink#pink-3-8) ссылка должна вести на страницу именно интенсива

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +        <a class="copyright__link" href="https://htmlacademy.ru"></a>
А где содержимое? Не должно быть совсем пустых элементов

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +              <a class="nav-list__link" href="https://htmlacademy.ru">Html Academy</a>
```suggestion
              <a class="nav-list__link" href="https://htmlacademy.ru/">HTML Academy</a>
```

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            </li>
Вот тут тоже у нас все эти страницы будут, нужно им адреса прописать сразу

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +        <div class="download-app__wrapper">
Вот тут понятно зачем обертка =)

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +              <img src="../img/platforms/apple-logo.svg" width="47" height="56" alt="Логотип Apple">
Смотри:
- у нас сервер запускается из папки `source`.
- `index.html` лежит в папке `source`.
- папка `img` тоже лежит в папке `source`.

Если ты пишешь `../`, то выходишь из папки, то есть выходишь из `source`. И там ищешь папку `img`. Ее там нет, а следовательно картинка не найдется.

Но! Ты наверняка скажешь, что все у тебя работает и картинки отображаются. Да! Потому что сервер запускается из `source` и выход из папки не срабатывает, так как это уже корневая папка сервера. И он дальше в корне ищет `img`.
Только так бывает не всегда. [В опубликованной на ГитХабе версии](https://htmlacademy-adaptive.github.io/1853291-pink-25/3/) картинок нет, потому что там страница лежит не в корне. И там то эта ошибка и проявляется.

В общем, вся эта тирада просто чтобы ты понимала как все это работает и почему в одном месте все ок, а в другом не ок. А путь надо правильно написать здесь и далее:

https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L46
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L49
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L190
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L195
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L200

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            <li class="platforms-list__item">
Не знаю, не слишком ли много получается разделений на блоки?
Можно же обойтись `download-app__list` и `download-app__item`.

Но это конечно сама смотри. Попробуй вообще так оставить, если увидишь, что неудобно, то блок выкинешь один.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +          <a class="download-app__link button-primary download-button" href="#">Скачать приложение</a>
Что-то я тут запутался в БЭМе.
`download-app__link` у нас будет чтобы настроить кнопку в этом блоке: ширину там прописать на весь контент и все такое.
`button-primary` выглядит странновато. Обычно бывает `button button--primary`. С другой стороны, если ты заводишь отдельный вид кнопки — ок. Если надо, то надо.
А зачем `download-button` я вообще не понял.

В общем, на данном этапе по идее должно было бы хватить каких-то двух классов: элемент и блок. Может, модификатор, но с ним спешить не обязательно сейчас.
А вот микс двух блоков не нравится.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +        <h2 class="visually-hidden">Основные особенности товара.</h2>
Вроде точки для интерактивных элементов.
Заголовки то обычные без точек живут как-то...

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            предложить!</p>
Какое-то странное форматирование. Можно так:
```suggestion
          <p class="subtitle">
            Устали от серости мегаполиса?
            Нам есть, что вам предложить!
          </p>
```

Ну или так:
```suggestion
          <p class="subtitle">Устали от серости мегаполиса? Нам есть, что вам предложить!</p>
```

А вообще, судя по форматированию текста, параграфов тут 2

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +        <div class="product-features__subtitle subtitle-wrapper">
Не понял зачем блок `subtitle-wrapper`. Почему бы не обойтись одним элементом?

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            </p>
А почему это не заголовки?
Хорошо же подходит

https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L67-L69
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L75-L77
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L83-L85

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +          </li>
Сейчас у меня закралась мысль, что ты побаиваешься использовать элемент в элементе и от этого миксуешь на каждый вложенный тег еще один блок и от него делаешь следующий элемент:
- product-features
  - product-features__list features-list
    - features-list__item features-item
      - features-item__title

Это очень неудобно будет )
Вполне легально, нормально и вообще адекватно сделать так:
```
        <ul class="product-features__list">
          <li class="product-features__item">
            <p class="product-features__title">
              Поднимает настроение
            </p>
            <p class="product-features__description">
              Приложение позволит вам победить осеннюю хандру и депрессию буквально в несколько кликов!
            </p>
          </li>
```

Элементы одного блока могут находиться на разных уровнях, в том числе вкладываться друг в друга.
Тут боюсь, что придется тебе пересмотреть всю страницу и подумать, где можно упростить и поубирать лишние блоки (на каждый блок кстати свой файл стилей будет, так что ты этим упростишь себе жизнь).

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +
А это что за дырка )
Если и делать пропуск строки, то после секции (но тогда между всеми надо, смотри насколько это удобно тебе)

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +      <section class="feedback slider">
Я знаю, что так делают в демке, но от подобного решения практическая польза почти нулевая.
Вот у тебя в таблице есть слайдер — и ты его даже не выделила (и не надо).

Микс таких блоков тебя скорее запутает. Разделять какие свойства слайдеру, а какие отзыву будет неудобно.

Лучше будет, если ты возьмешь `slider-pagination` и переиспользуешь это блок под таблицей. Вот это будет хорошо и полезно.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            <li class="slider-pagination__item"></li>
Вообще, они кликабельны. Тыкаешь на кружок — перемещаешься к слайду. Так что это интерактивный элемент. И тем более он не может быть пустым

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +              <th class="price-table__category price-table__category--special">
Во, отлично. Хорошо применить модификатор с самого начала — это хорошо =)

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            </tr>
С модификаторами все супер, но как незрячий услышит что там у нас есть, а чего нет?
Пускай элемент и не интерактивный, но доступный текст все равно нужен.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +          </ul>
Вот тут такие же на вид кнопки, как `slider-pagination`. Переиспользуй здесь тот блок, только здесь возможно будет другой набор подписей и активный элемент другой.
Но визуально они идентичны, а значит это по БЭМу тот же бло.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            <a class="contacts-item__link" href="tel:+7-812-555-66-66">+7 (812) 555-66-66</a>
```suggestion
            <a class="contacts-item__link" href="tel:+78125556666">+7 (812) 555-66-66</a>
```

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            <a class="contacts-item__link" href="mailtomail@htmlacademy.ru">mail@htmlacademy.ru</a>
```suggestion
            <a class="contacts-item__link" href="mailto:mail@htmlacademy.ru">mail@htmlacademy.ru</a>
```

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +            <p class="contacts-item__link">ул. Большая
Здесь я бы тоже сделал ссылку с заглушкой. Вместо заглушки в реальности скорее всего стояла бы ссылка на гугл/яндекс карту с маршрутом или просто с точкой.

2022-04-02 22:12 UTC, arturtrifonov commented on source/index.html
> +        <div class="contacts__list contacts-list">
Можно было бы сделать посемантичнее.
Вот сама же пишешь в элементе, что список...

> Подсказка: есть даже такой тип списка, с парой типа "ключ: значение" для каждого айтема

2022-04-02 22:12 UTC, wrgraff commented on source/index.html
> +          <img src="https://via.placeholder.com/145x40" alt="Логотип Пинк">
А где ширина и высота?
И еще такое есть:
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L11
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L89
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L174
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L182

2022-04-02 22:12 UTC, wrgraff commented on source/index.html
> +            <a class="socials-item__link socials-item__link--vk" href="#">
А зачем нам модификаторы в ссылках, если картинка стоит прямо в коде?
А должна ли стоять картинка прямо в коде? Нам бы это понадобилось, если бы у нее менялся цвет при взаимодействии.

Надо или добавить скрытую подпись вместо картинки, или убрать модификатор
(цвет у них не меняется, поэтому если ты сделаешь вариант номер 2, я опять докопаюсь — имей ввиду)

2022-04-02 22:12 UTC, wrgraff commented on source/index.html
> +        <h2 class="visually-hidden">Мы в социальных сетях.</h2>
Так у тебя выходит, что этот заголовок и на ссылку академии распространяется.
Может, ну его? Убрать просто

2022-04-02 22:12 UTC, wrgraff commented on source/index.html
> +              <img src="../img/platforms/android-logo.svg" width="43" height="47" alt="Логотип Android">
Годятся ли эти картинки на роль контентных? Или же у нас есть возможность немного пооптимизировать скорость загрузки и отправить их в фон?
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L42-L50

2022-04-02 22:12 UTC, wrgraff commented on source/index.html
> +              <img src="../img/platforms/microsoft-logo.svg" width="44" height="41" alt="Логотип Microsoft">
Подозреваю, что эти логотипы — ссылки на приложения в соответствующих магазинах
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/feaa8a441234409a37128be9e831c67d5e855854/source/index.html#L42-L50

2022-04-02 22:16 UTC, wrgraff commented
А, вот еще. Коммитить желательно в одном стиле:
<img width="273" alt="изображение" src="https://user-images.githubusercontent.com/37917037/161403060-51815e5b-ba3a-4f87-aa77-a5e5e2f6ef41.png">

Выбери один язык и одну стилистику — с прописной или с заглавной.
Но это уже на будущее, не пытайся менять: можно дел натворить.

2022-04-03 12:48 UTC, zazuzai commented on source/index.html
> +            </p>
Валидатор ругается(
![Screenshot 2022-04-03 at 14 38 39](https://user-images.githubusercontent.com/90500325/161428841-604d3863-6580-46ac-9f7a-db6b0e789b75.png)
(

2022-04-03 12:49 UTC, zazuzai commented on source/index.html
> +          </li>
`Сейчас у меня закралась мысль, что ты побаиваешься использовать элемент в элементе и от этого миксуешь на каждый вложенный тег еще один блок и от него делаешь следующий элемент`

Да, это так:(((
попробовала переделать

2022-04-03 12:51 UTC, zazuzai commented on source/index.html
> +              <img src="../img/platforms/microsoft-logo.svg" width="44" height="41" alt="Логотип Microsoft">
Переделала, правда тогда я не понимаю, для чего эта кнопка "Скачать приложение" сверху (если ссылки на скачивание будут по картинкам)

2022-04-03 12:53 UTC, wrgraff commented on source/index.html
> +            </p>
Что за тег такой )
Заголовки это ж h1-h6

2022-04-03 13:13 UTC, zazuzai commented on source/index.html
> +            </p>
(⊙_⊙) 
и правда...

2022-04-03 22:28 UTC, arturtrifonov commented on source/index.html
> +            </button>
А как какую-то информацию получить из текста "переключить отзыв"?
Можно просто "отзыв №1" и так далее. Нужно же понять какой отзыв включится по нажатию кнопки

2022-04-03 22:28 UTC, arturtrifonov commented on source/index.html
> +          <div class="feedback__pagination slider-pagination">
А чего от списка отказалась? Были бы кнопки в пунктах, норм тоже.
Ведь ты же изначально список делала — была значит в этом какая-то логика )

2022-04-03 22:28 UTC, arturtrifonov commented on source/index.html
> +            </button>
Чего-то с вложенностью только случилось
```suggestion
        <div class="price__pagination slider-pagination">
          <button class="slider-pagination__toggle" type="button">
            <span class="visually-hidden">Переключить слайд.</span>
          </button>
          <button class="slider-pagination__toggle slider-pagination__toggle--current" type="button">
            <span class="visually-hidden">Текущий слайд.</span>
          </button>
          <button class="slider-pagination__toggle" type="button">
            <span class="visually-hidden">Переключить слайд.</span>
          </button>
```

2022-04-03 22:28 UTC, wrgraff commented on source/index.html
> +          <ul class="header-nav__list nav-list">
Ты вот если тег убираешь, то вложенность сразу поправляй.
Это в целом полезная привычка — поддерживать форматирование кода в хорошем виде. Но и на защите к этому почти наверняка придерутся

2022-04-03 22:28 UTC, wrgraff commented on source/index.html
> +              <a class="nav-list__link" href="https://htmlacademy.ru">HTML Academy</a>
```suggestion
              <a class="nav-list__link" href="https://htmlacademy.ru/">HTML Academy</a>
```

2022-04-03 22:28 UTC, wrgraff commented on source/index.html
> +        <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">Разработано</a>
Разработано кем? Ведь скринридер так и скажет: "Ссылка: Разработано".
А у нас информация ведь есть, что разработано академией. Это и нужно передать в доступности.

Подсказываю: можно часть текста спрятать в `span.visually-hidden`, а часть останется видимой. `span` никак не отраится на чтении ридером

2022-04-03 22:28 UTC, wrgraff commented on source/index.html
> +              </a>
Вооо, красота!
Молодчина

2022-04-03 22:28 UTC, wrgraff commented on source/index.html
> +            </p>
Не, `<title>` есть, он в `<head>` используется

2022-04-03 22:30 UTC, wrgraff commented on source/index.html
> +          </li>
Насколько вижу, все получилось! Говорил же, что справишься

2022-04-03 22:42 UTC, wrgraff commented on source/index.html
> +              </th>
Не сразу заметил, что тут все элементы — заголовочные ячейки. Не надо так )
Вот "Розовый фильтр" и правда подходит на роль заголовка (у нас получается есть целый хэдер сверху и в каждой строке одна заголовочная ячейка).
А вот остальные надо переделать бы в обычные `<td>`

2022-04-03 22:42 UTC, wrgraff commented on source/index.html
> +              <img src="../img/platforms/microsoft-logo.svg" width="44" height="41" alt="Логотип Microsoft">
А там насколько я помню из ранних версий ТЗ (не уверен, что это не убрали), подразумевается, что сайт определяет платформу посетителя и основная кнопка ведет на соответствующий магазин.
Но так как это наука не точная — на всякий случай остаются и другие ссылки, куда я могу нажать если вдруг мой андроид показался сайту виндой.

> Что там должно быть на десктопе история умалчивает... Думаю, настолько UX этого псевдосайта никто не продумывал

2022-04-03 22:43 UTC, wrgraff approved these changes
Ну я еще кой-чего нашел, но прям критичных моментов нет.
Можешь поправить и со следующим заданием, чтобы нам не замедляться с домашкой этой.
Главное вообще форматирование пофиксить.

2022-04-03 22:45 UTC, merged