Разметка внутренних страниц
htmlacademy-adaptive/1853291-pink-25 pull request #4
Opened 2022-04-04 21:43 UTC by zazuzai

2022-04-05 18:31 UTC, wrgraff requested changes
В целом неплохо выглядит.
Обрати внимание, что некоторые комментарии в форме вопроса. Это не требование поправить что-то в вопросительной форме, а можно правда ответить и аргументировать свое решение. Возможно, я чего-то не понял в задумке

2022-04-05 18:31 UTC, arturtrifonov commented on source/index.html
> +        </a>
Лучше не писать одну часть содержимого в строке, а другую на новой строке.
Когда код читаешь, если тег закрывается на отдельной строке, обычно не ищешь после открытого тега еще содержимое. Поэтому лучше так (например):
```suggestion
        <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive">
          Разработано
          <span class="visually-hidden">HTML Academy.</span>
        </a>
```

2022-04-05 18:31 UTC, arturtrifonov commented on source/catalog.html
> +    <title>HTML Academy: Пинк</title>
Кстати, `<title>` хорошо бы разный написать. Он должен соответствовать контенту страницы, а не сайту в целом

2022-04-05 18:31 UTC, arturtrifonov commented on source/catalog.html
> +          </li>
Но здесь активная страница уже не главная

2022-04-05 18:31 UTC, arturtrifonov commented on source/catalog.html
> +          <h2 class="catalog__title">Фотографии пользователей</h2>
А чем плох был бы этот заголовок сам в качестве `<h1>`? "Галерея" и "Фото пользователей" в общем-то по смыслу почти одно

2022-04-05 18:31 UTC, arturtrifonov commented on source/catalog.html
> +          </h3>
Заголовки должны кратко и емко описывать контент, который идет за ними. Такой длинный лозунг не очень то хорошо подходит для описания содержимого.

Аналогичная ситуация с другим заголовком ниже:
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/91c10f802bc3716e9e6a9c8b68a7529ceed4e302/source/catalog.html#L214-L217

<details>

<summary>Менее важная часть</summary>

К тому же, следующий заголовок снова 2 уровня. Не совсем тогда понятно, если весь контент ниже попадает под оба заголовка — зачем они оба? Должно быть что-то подобное ведь:
- Заголовок 1
  - Заголовок 2
    Контент
    - Заголовок 3
      Контент
    - Заголовок 3
      Контент
  - Заголовок 2
    - Заголовок 3
      Контент
    - Заголовок 3
      Контент
      
То есть, заголовки 3-го уровня дополнительно делят контент на какие-то части под заголовком второго уровня. Просто так один он там не очень полезен будет.

</details>

2022-04-05 18:31 UTC, arturtrifonov commented on source/catalog.html
> +            <img class="photo-card__img" src="https://via.placeholder.com/320x137" width="320" height="137" alt="Фото 1.">
Такой `alt` не очень хорошее представление о содержимом фото представит (то же справедливо и для других фото).
Хорошие примеры описаний можно [посмотреть на сайте Weblind](https://weblind.ru/inner.html#image-content)

2022-04-05 18:31 UTC, arturtrifonov commented on source/catalog.html
> +              <div class="photo-card__heading">
Я запутался. Сперва идет обертка `photo-card__description`, а затем внутри этого описание все обернуто в `photo-card__heading`. А зачем нам аж 2 обертки одна в другой?

2022-04-05 18:31 UTC, arturtrifonov commented on source/catalog.html
> +                  назад)
Так, а тут для чего дополнительные `<span>`'ы?

2022-04-05 18:31 UTC, arturtrifonov commented on source/catalog.html
> +                  <span class="like__counter">215</span>
Тут тоже не очень понятно, почему 2 разных спана, а не один параграф?

2022-04-05 18:31 UTC, wrgraff commented on source/catalog.html
> +            <button class="upload-photo__button upload-photo__button--post" type="submit">Запостить</button>
Если мы сабмитим кнопкой форму, то где же сама форма?
Кажется, потерялась где-то.

2022-04-05 18:31 UTC, wrgraff commented on source/catalog.html
> +            <button class="upload-photo__button upload-photo__button--cancel" type="button">Отмена</button>
Можно использовать `type="reset"`.

2022-04-05 18:31 UTC, wrgraff commented on source/catalog.html
> +              </div>
Как-то странно.
Если бы это была иконка — стоило ли бы ради нее создавать `<div>`, внутри которого вставлять изображение? Сразу же хочется спросить:
- а почему не вставить картинку без дива?
- а почему вообще не сделать ее псевдоэлементом?

Вторая часть проблемы же заключается в том, что ответ на второй вопрос заключается вот в чем: нельзя сделать псевдоэлементом, потому что иконка меняет цвет вот здесь:
<img width="297" alt="изображение" src="https://user-images.githubusercontent.com/37917037/161821973-b13bf92e-8577-4bd2-9eb3-29bf2e30e2f1.png">
А почему она меняет цвет? Потому что это не иконка, а кнопка, которая работает как вкладка и переключает нас между тремя разными ползунками, которые отвечают за кадрирование, фильтр и контраст.

Получается, это должна быть кнопка, а вовсе не див — и вот в ней уже будет иметь смысл вставлять `<svg>`.

2022-04-05 18:31 UTC, wrgraff commented on source/catalog.html
> +              </div>
Есть `<input type="range">`. Для двойного слайдера с выбором цены он не подходил, а для одного ползунка — вполне.

https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/91c10f802bc3716e9e6a9c8b68a7529ceed4e302/source/catalog.html#L225-L231
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/91c10f802bc3716e9e6a9c8b68a7529ceed4e302/source/catalog.html#L237-L243
https://github.com/htmlacademy-adaptive/1853291-pink-25/blob/91c10f802bc3716e9e6a9c8b68a7529ceed4e302/source/catalog.html#L249-L255

Да, его будет чуть посложнее оформить, но зато верстка будет аккуратнее, ползунок будет рабочий, форма реально будет отправлять данные о примененных фильтрах, а ты научишься работать с таким типом инпутов.

Так что подумай, может оно того и стоит =)

2022-04-05 18:31 UTC, wrgraff commented on source/form.html
> +          <li class="nav-list__item nav-list__item--current">
Тут тоже точно не главная активна )

2022-04-05 18:31 UTC, arturtrifonov commented on source/form.html
> +      </div>
У меня есть некоторое подозрение, что эти элементы оборачивать одним дивом не стоит...
Они же прям один в одном месте, а другой в другом:
<img width="337" alt="изображение" src="https://user-images.githubusercontent.com/37917037/161823332-72a58da1-1361-4b95-95e6-3180db02eacd.png">

Поэтому я и говорил, что с обертками лучше не спешить, а обойтись семантикой. Лучше их сделать недостаточно и добавить когда надо, чем потом разбираться с лишними.

2022-04-05 18:31 UTC, wrgraff commented on source/form.html
> +          </div>
Может быть, сейчас это усложнит ситуацию, но в реальном проекта я бы выделил еще блок `field` отдельно.
Все-таки поля могут где-то встречаться без филдсетов. Полезный БЭМ-блок.

2022-04-05 18:31 UTC, wrgraff commented on source/form.html
> +                <input class="radio__input" type="radio" name="radio" value="iOS" checked>
`name` какой-то не очень удачный )
Нам придет при отправке этой формы нечто такое: `radio: iOS`. Кажется, можно поосмысленнее сделать имя =)

2022-04-05 18:31 UTC, wrgraff commented on source/form.html
> +        <div class="contest-form__submit submit-wrapper">
Зачем `submit-wrapper` нужен, если все элементы внутри все равно идут от блока `contest-form`?

2022-04-05 18:31 UTC, wrgraff commented on source/form.html
> +          <textarea class="form-group__input" name="feedback-text" id="textarea-id" rows="5" placeholder="Можно прям в красках, не стесняясь в выражениях"></textarea>
Лучше не давать такие абстрактные id. Сайт конечно тренировочный, но лучше приучаться писать как-то сразу осмысленно

2022-04-05 19:05 UTC, zazuzai commented on source/catalog.html
> +                  назад)
Подумала, что теоретически сюда должны приезжать разные данные каждый раз, например как в корзине со стоимостью товара, когда есть штуки и сумма, а тут есть число и единица времени.

2022-04-05 19:12 UTC, zazuzai commented on source/catalog.html
> +              </div>
начала думать про инпуты, а потом прочитала в тз, что `инструмент обработки изображений в блоке перед подвалом реализовывать не нужно`
но сейчас понимаю, что реализация - это про само кадрирование, а не про ползунки и лень не прокатит:(

2022-04-05 19:51 UTC, wrgraff commented on source/catalog.html
> +              </div>
Ну я не уверен, что эти кругляки верстать кнопками тоже прям удобно уж )

2022-04-05 20:00 UTC, arturtrifonov commented on source/catalog.html
> +                  назад)
Ой. Не заморачивайся пока настолько )
Вполне вероятно, например, что эта строка будет формироваться и приходить целиком

2022-04-06 15:50 UTC, zazuzai commented on source/catalog.html
> +              <div class="photo-card__heading">
делала обёртку для имени пользователя и даты поста, но не досмотрела и div "разъехался". поправила

2022-04-06 15:52 UTC, zazuzai commented on source/catalog.html
> +            <img class="photo-card__img" src="https://via.placeholder.com/320x137" width="320" height="137" alt="Фото 1.">
спасибо! у меня был вопрос по этим описаниям как раз. пока сделала краткие

2022-04-06 15:53 UTC, zazuzai commented on source/index.html
> +        </a>
стоит ли поправить это во всем документе, чтобы было единообразие? (в смысле чтобы всегда текст внутри параграфов, спанов, кнопок и т.п. был с новой строки)

2022-04-06 21:15 UTC, wrgraff commented on source/index.html
> +        </a>
Нет, не обязательно.
Вообще, я для себя лично придумал правило:
> Если внутри тега есть другой тег, то его содержимое должно быть на новой строке

Но это мое правило, а не твое =) Ты можешь другими принципами руководствоваться.
Единственное, чего бы не хотелось — это комбинации, когда часть содержимого в строке, а часть на новой

2022-04-06 21:35 UTC, wrgraff approved these changes
👍

2022-04-06 21:35 UTC, wrgraff commented on source/catalog.html
> +                <p class="like__counter">Нравится:&nbsp;356</p>
Наверное, в таком случае лучше не символом воспользоваться, а через стили задать `nowrap`

2022-04-06 21:35 UTC, merged