Стилизация страниц
htmlacademy-adaptive/1853291-pink-25 pull request #5
Opened 2022-04-10 20:41 UTC by zazuzai

Не разобралась с фоновым изображением (фото в темно-синем фильтре), которое видно под шапкой, когда меню навигации закрыто. Наверное надо переносить его в хэдер и тогда в хэдер уедет вся секция про загрузку приложения с главной страницы.

2022-04-11 19:23 UTC, wrgraff requested changes
Вообще, сайт выглядит очень складно для такого этапа.
Но технические всякие помарки я все равно нашел =)

Ты молодец — проделала большую работу, и дальше тебе придется делать уже меньше (правда, обычно на этом этапе сайты выглядят как монстр Франкенштейна на начальном этапе "сборки"). Теперь нужно только чуть поправить там, чуть поправить сям — и все. Это не страшно.

Кое-что из проблем, что не привязать к конкретному месту в коде:

- Насколько вижу, картинка `source/img/download-app/screen.png` не используется. Его лучше удалить тогда (вроде даже в критериях что-то такое было)
- Надо запустить локально тест (`npm run lint`) и посомтреть, что он выдает. Проверка по линтерам должна обязательно проходить (на ГитХабе это тоже видно)
![изображение](https://user-images.githubusercontent.com/37917037/162813825-030cc1af-f9db-48f1-8451-8a155cf2cd60.png)

2022-04-11 19:23 UTC, arturtrifonov commented on source/index.html
> +      <section class="download-app intro">
Есть сомнения, что этот блок будет похож на другие `intro`.
Если у них будет разная сетка и/или отступы, то такой микс скорее помешает. И может нарушить независимость блоков (скорее, односторонне, но все же).

В общем, я бы поостерегся таких миксов, особенно пока опыта не так много

2022-04-11 19:23 UTC, arturtrifonov commented on source/index.html
> +            <img class="product-features__img" src="https://via.placeholder.com/157x287" width="157" height="280" alt="Пример использования фильтра и комментариев в приложении Пинк.">
Так неправильно же )
Надо или так:
```suggestion
            <img class="product-features__img" src="https://via.placeholder.com/157x287" width="157" height="287" alt="Пример использования фильтра и комментариев в приложении Пинк.">
```

Ну или так:
```suggestion
            <img class="product-features__img" src="https://via.placeholder.com/157x280" width="157" height="280" alt="Пример использования фильтра и комментариев в приложении Пинк.">
```

Что в общем то не так и важно )

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/fonts.scss
> +}
Отлично, шрифты от путей до набора свойств подключены без ошибок.

Но, в отличие от первого уровня верстки, на втором все еще требуется подключать 2 формата шрифтов. Про это у нас критерий [Б9](https://up.htmlacademy.ru/adaptive/25/criteries#b9)

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/style.scss
> +@import "./page.scss";
А почему у тебя пути написаны в разном стиле?
Почти везде с точкой путь. Надо тогда не почти везде, а везде сделать =)
```suggestion
@import "./fonts.scss";
@import "./common.scss";
@import "./page.scss";
```

Ну или поудалять везде. Тут как хочешь

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/style.scss
> +@import "./blocks/main-index/slider-pagination.scss";
Лучше не создавать и не подключать пустой файл.
Будет надо — создашь и подключишь тогда, когда такая нужда возникла.

Если даже для блока не будет стилей и он так и останется без файла... Да ну и ладно, кого это беспокоит. 

> Я, например, когда верстаю, пишу классы элементов и миксую с блоками _всегда_. Классов выходит много, и они помогают не только оформлять, но и видеть структуру. А так как их много, некоторые оказываются вовсе без стилей.

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/style.scss
> +@import "./blocks/header/nav-list.scss";
Ох, стремление к упорядочиванию и группировке — это хорошо, но тут ты по незнанию перегнула палку )

@import "./blocks/`header`/header.scss";
@import "./blocks/`header`/header-nav.scss";
@import "./blocks/`header`/nav-list.scss";

Во-первых, чисто формально тебя скорее всего завернут по критерию [Б13](https://up.htmlacademy.ru/adaptive/25/criteries#b13), так как у нас определена структура: сперва папка `blocks` и в ней блоки. Без дополнительных папок.
Но следование критериям по правде говоря интересует меня куда меньше, чем следование лучшим практикам и логике. Так вот.

Во-вторых, в таком разделении блоков нет большого смысла. БЭМ добивается двух основных задач: переиспользуемости и независимости. Это значит, что БЭМ-блок технически не должен относиться к какому-то типу или виду, к какому-то разделу или отделу сайта и прочее. То есть, мы понимаем, конечно, что какой-нибудь `footer` мы никуда кроме низа страницы не поставим. Но технически он должен быть как блок лего: мы совершенно неуместно можем влепить его куда-нибудь в середину страницы. И помешать это сделать нам должен здравый смысл, но не техническое ограничение.

Кстати, из тех блоков, что ты выделила, на самом деле далеко не все будут иметь свое одно единственное место. Вот у тебя лежит `feedback` в папке `main-index`. А появится у сайта страница "о компании" и туда захотят поставить обратную связь. Логично ли тогда, что он относится именно к `main-index`? Не очень, кажется =)
И так можно наверное 90% твоей структуры опровергнуть.

Если думаешь, что по папкам легче будет искать блоки... Не будет. Даже если их много, редактор их сортирует по алфавиту. Всегда легко найти нужный файл. А вот если ты точно не знаешь в какой он папке и надо заглянуть в несколько... В общем, я так делал какое-то время — это прям вот вообще неудобно. Можешь потом попробовать, только не на курсе )

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/common.scss
> +
Откуда у тебя дырки в коде?
Я вижу, что ты группируешь стили, и это замечательно. Но пропуск строки там один нужен )

Вообще, имей ввиду: может быть много замечаний к тому, что код оформлен "как-то не так".
Это не просто так. Даже если твоя верстка идеальна, а код похож на черти что, это будет красным светом для любого хорошего работодателя. Потому что для работы в команде очень важно писать код аккуратно (а работы не в команде не бывает)

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/common.scss
> +.slogan {
Ммм, если `visually-hidden` можно выделить как нечто особое, эдакий утилитарный стиль, то `slogan` уже явно БЭМ-блок. Он может быть без элементов, но все равно блок.

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/common.scss
> +  font-family: "Open Sans";
Тут не пройдешь критерий [Б10](https://up.htmlacademy.ru/adaptive/25/criteries#b10). Нужно указывать запасной шрифт и семейство.

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/common.scss
> +body {
Вообще, если у тебя есть класс на `body` (а он есть), то можно же им воспользоваться.

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/common.scss
> +$font-color-accent: #d22856;
Переменные обычно складывают в отдельный файл `variables`.
Их по ощущениям маловато, кстати.

А еще для таких сайтов, у которых в основе никакой дизайн-системы нет, я бы рекомендовал делать не именованные цвета (типа как сейчас у тебя: для шрифта, для фона, и так далее), а просто [палитру использовать абстрактную](https://frontend-design.notion.site/a8b8c114d0dc40aab87a54e8cc8dd859).

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/common.scss
> +
И тут дырка... Давай вместо нее обнулим отступы `margin` у `<body>` =)

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/modal.scss
> +
Один пропуск строки должен быть между стилями

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/product-features.scss
> +    h3 {
Какой-то непонятный отступ. Вложенные теги пишутся с тем же отступом, что и правила. То есть, `h3` должен быть на уровне с `padding-bottom`

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/product-features.scss
> +    h3 {
Вот тут плохо, что выбираешь стилизацию по тегу в то время, когда у тебя есть класс `.product-features__title` (по-моему, это не один раз так — посмотри, где еще есть).

Стилизация по классу всегда первый выбор. Вложенный тег создает более специфичный селектор и потом это может аукнуться.
На самом деле, даже если у тебя нет класса на каком-то теге, который нужно стилизовать — лучше не полениться и пойти в разметку, чтобы дать ему класс.

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/product-features.scss
> +  background: #f2f2f2;
Лучше использовать `background-color`.
`background` — это составное свойство. Конечно, сейчас и в большинстве случаев оно ничего не сломает, но иногда тебе захочется переписать только цвет фона для какого-то модификатора, напишешь по привычке `background` и он сотрет все остальное: картинку и ее правила расположения.

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/product-features.scss
> +    }
Вот тут через вложенность более-менее оправданно: типа, внутри другой блок, и чтобы его не трогать...

Но что-то мне не нравится так )
Я бы наверное переделал разметку как-нибудь так:

```html
<div class="product-features__subtitle subtitle">
  <p class="subtitle__text">
    Устали от серости мегаполиса?
  </p>
  <p class="subtitle__text">
    Нам есть, что вам предложить!
  </p>
</div>
```

И тогда бы отступы через `subtitle__text` правил в этом отдельном блоке. Только у тебя там `subtitle` переиспользуется, так что смотри какой блок создать под это. У меня это просто пример

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/price.scss
> +  background-color: #f2f2f2;
Не первый раз вижу цвет. Чего бы его не забросить в переменную?

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/price-table.scss
> +  height: 21px;
Как видишь, ячейкам на твои размеры абсолютно параллельно =)

![изображение](https://user-images.githubusercontent.com/37917037/162808360-2f9b584a-5fc9-493e-8c71-e1de9d756672.png)

Можно их смело удалить. Не путай размер фоновой картинки и размер самого элемента

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/price-table.scss
> +  background-repeat: no-repeat;
Вот эта "пачка" стилей одинакова и для `price-table__option--no` и для `price-table__option--yes`

Почему бы не вынести это в `.price-table__option` и не повторять дважды?
Оно конечно еще применится и на первую ячейку с заголовком, но не похоже, что это как-то ей помешает.
А так старайся не повторять один и тот же код, когда... Ну, когда можно не повторять )
Иногда есть более важные цели, конечно.

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/price-table.scss
> +    }
Что-то с отступами тут...
```suggestion
  p {
    padding: 0;
    margin: 15px 0 0 0;

    font-weight: 300;
    font-size: 24px;
    line-height: 30px;
  }
```

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/feedback-item.scss
> +  }
А зачем они вложены внутрь `feedback-item`?
Мы увеличили этим специфичность. Как правило, мы стараемся этого не делать, а тут вроде и просто через классы можно...

2022-04-11 19:23 UTC, arturtrifonov commented on source/sass/blocks/main-index/download-app.scss
> +  margin-right: 0px;
Нули у нас по правилам оформления пишутся без единиц измерения:
```suggestion
  margin-right: 0;
```

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-index/download-app.scss
> +.download-app__description{
```suggestion
.download-app__description {
```

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-index/download-app.scss
> +
Обязательно разберись с лишними пустыми строками

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-index/download-app.scss
> +  background-image: url("../img/platforms/windows-logo.svg");
Тут я тебе рекомендую схитрить и сделать 3 элемента одинаковой ширины и высоты, а картинку расположить по центру и без повторений.
Так ссылки будут одинаковые и хорошо центрироваться, укладываться в сетку и прочее.

Вообще, почти всегда иконки вписаны в квадраты и размер элемента обычно как раз соответствует квадрату (ну или прямоугольнику), а не иконке. Да и менять их попроще так.

Например, вот так выглядят иконки Material design от Google:
![изображение](https://user-images.githubusercontent.com/37917037/162811249-a454b843-786e-4572-afae-0eefa7418f57.png)

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-index/contacts.scss
> +      a {
Вот тут заигралась и сделала тройную вложенность, что нарушает [критерий Д10](https://up.htmlacademy.ru/adaptive/25/criteries#d10).
Ну и вообще не надо так делать )

Лучше всего создать классы (это если их нет) и задать стили через них. А от вложенности максимально избавиться.

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-form/form-group.scss
> +.form-app {
Ой, `form-achievement` и `form-app` — это БЭМ-блоки, которые должны [находиться в файлах своих блоков](https://up.htmlacademy.ru/adaptive/25/criteries#b13).

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-form/contest-form.scss
> +}
Ох. Все смешалось в доме Облонских...
Куча элементов от других блоков находится в файле блока `contest-form`

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-form/contest-form.scss
> +textarea::placeholder {
Даже если ты берешь плейсхолдер от тега, это все равно [стилизация по тегу](https://up.htmlacademy.ru/adaptive/25/criteries#d16). А так нельзя

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-form/contest-form.scss
> +  margin-bottom: 26px;
Размеров у БЭМ-блоков, да и отступов тоже у тебя нет. Я так понимаю, это осознанно и ты понимаешь почему размеры и отступы нельзя ставить блокам (да?).

> 💡 Здесь надо отметить, что на защите тебя скорее всего по этим нюансам проверять не будут, потому что в академии ограничиваются проверкой нейминга и файловой структуры по БЭМ.
>
> Поэтому, тебе нужно будет сообщить мне — хочешь ли ты попробовать по максимуму соответствовать принципам БЭМ, или же, если это пока кажется сложным, мы можем ограничиться более простыми правилами (ты так же можешь отказаться от соблюдения этого позже, если станет тяжело).

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-catalog/photo-card.scss
> +}
Для блока `like` придется создать отдельный файл

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-catalog/photo-card.scss
> +  margin-top: 27px;
Отступ у блока лучше не делать. Замиксуй его с элементом `photo-card` и ему сделай отступ.

**Если по этому моменту есть вопросы — обязательно дай знать!**

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/main-catalog/editing-tools.scss
> +  margin: 0;
Есть проблема не только с установкой, но и с обнулением отступов у БЭМ-блоков. Хотя, казалось бы обнуление — это же не установка отступа, а удаление?..

Но суть проблемы в том, что обнуление внутри блока точно так же может случайно переписать свойства элемента, как и указание какого-то конкретного размера.
Потому что технически мы не обнуляем, а назначаем отступ, равный нулю. Поэтому даже обнуления придется делать через элементы.

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/logo.scss
> +  background-color: rgba($color: #000000, $alpha: 0.3);
Можно еще попроще делать:
```suggestion
  background-color: rgba(#000000, 0.3);
```

А еще можно использовать переменную, например так (ее конечно создать надо еще):
```suggestion
  background-color: rgba($color-black, 0.3);
```

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/header/nav-list.scss
> +      a {
Оп, опять тройная вложенность. Аналогично, как и раньше: рекомендую делать через классы.

2022-04-11 19:23 UTC, wrgraff commented on source/sass/blocks/footer/footer.scss
> +  cursor: pointer;
Это же ссылка? Тогда и так будет `pointer`. Если ссылка без `href`, то не будет, но она тогда и не кликабельная, а значит ей такой курсор не нужен.

2022-04-11 19:26 UTC, wrgraff commented
> Не разобралась с фоновым изображением (фото в темно-синем фильтре), которое видно под шапкой, когда меню навигации закрыто. Наверное надо переносить его в хэдер и тогда в хэдер уедет вся секция про загрузку приложения с главной страницы.

Я думаю, что лучше разбираться с этим в моменте, когда мы будем делать сетки. Потому что основная сложность будет с тем, как все это будет перестраиваться и меняться.
Когда ты поймешь как именно это будет работать — тогда будет точно понятно, как быть с фоном.

Скорее всего, там придется что-нибудь дополнительно обернуть.

2022-04-13 21:56 UTC, zazuzai commented on source/sass/style.scss
> +@import "./blocks/header/nav-list.scss";
думала, что будет удобнее искать, ага
переделала

2022-04-13 22:31 UTC, zazuzai commented on source/sass/common.scss
> +$font-color-accent: #d22856;
переменных будет больше, стилизация же только началась)
про цвета не очень понимаю, как мне сейчас быть - у меня они разные и высталять оттенки числами не получится. указывать их название тоже неправильно вроде (где-то в материалах было, что называть blue, когда оно теоретически может стать yellow - не самая удачная идея).
или ты в принипе о том, что мне надо убрать из имени переменной слово шрифт и оставить только primary, secondary и т.п.?

2022-04-13 22:42 UTC, zazuzai commented on source/sass/blocks/main-form/contest-form.scss
> +  margin-bottom: 26px;
ну сейчас размеров у меня почти нигде нет, потому что пока непонятно, как их указывать (вернее понятно, что через медиа-выражения это надо будет делать и они будут меняться),
но про блоки я понимаю, что раз блок - самостоятельная единица, то его нельзя отступами ни к чему внешнему привязывать, так?

2022-04-13 22:46 UTC, zazuzai commented on source/sass/blocks/main-catalog/photo-card.scss
> +  margin-top: 27px;
с миксами сложно:( я смотрю на примеры, которые есть в статье и понимаю, чего там и как, но у самой приидумать как замиксовать мозгов не хватает

2022-04-14 16:37 UTC, wrgraff commented on source/sass/fonts.scss
> +    url("../fonts/opensans.woff") format("woff");
Я обычно так делаю, чтобы и линтер не ругался, и строки вместе стартовали:

```suggestion
  src:
    url("../fonts/opensans.woff2") format("woff2"),
    url("../fonts/opensans.woff") format("woff");
```

А ты молодец, все отлично со шрифтами

2022-04-14 16:37 UTC, wrgraff commented on source/sass/style.scss
> +@import "./blocks/variables.scss";
Переменные это не блок =)
И лучше их подключать вообще самыми первыми, так как там кода по сути и нет, а есть то, что нужно для кода.

2022-04-14 16:37 UTC, wrgraff commented on source/sass/common.scss
> +$font-color-accent: #d22856;
Мммм, ну да, но нет =)

> переменных будет больше, стилизация же только началась)

Я уже видел в стилях один и тот же оттенок серого, который мог бы стать переменной.

> про цвета не очень понимаю, как мне сейчас быть - у меня они разные и высталять оттенки числами не получится. 
> или ты в принипе о том, что мне надо убрать из имени переменной слово шрифт и оставить только primary, secondary и т.п.?

Боюсь, что более-менее адекватно только числами и получится. Конечно, это не будет такая ровная схема с плавным переходом, как в примере из шпаргалки, но это хоть какой-то способ расписать те 15 оттенков серого (прочих цветов обычно поменьше), что есть в макете и при этом понимать хотя бы примерно как они друг к другу относятся.
Есть еще система именованных цветов, типа `font-primary`, `font-primary-hover`, `background-base`, `background-base-hover` и прочее. Но такое возможно только при наличии дизайн-системы, здесь макет совершенно бессистемный в этом плане.

> указывать их название тоже неправильно вроде (где-то в материалах было, что называть blue, когда оно теоретически может стать yellow - не самая удачная идея).

Лучше оставлять абстрактные имена, конечно. Но если говорить начистоту...
Есть как минимум черный, белый и серая палитра между ними — они никуда не денутся. Странно представить, что эти нейтральные цвета могут быть изменены на что-то совершенно другое (ну добавят в серый голубой тон — все равно он серым будет). Так что `white`, `black` и `gray` спокойно можно использовать.
Другие цвета конечно лучше не использовать, но вообще... Смотри, такой ли уж большой грех, если мы делая сайт для условного Альфа Банка назовем переменную `red`? Что же такое должно произойти, чтобы банк перестал использовать свой основной цвет бренда? И если это будет такой глобальный ребрендинг — останется ли вообще сайт или будет создан новый?

2022-04-14 17:06 UTC, arturtrifonov commented on source/sass/blocks/price-table.scss
>    p {
Но от стилизации через вложенность я бы и тут избавился, и вообще избавился бы от нее по максимуму (вот прям пока не прижмет — не использовать)

2022-04-14 17:06 UTC, arturtrifonov commented on source/sass/blocks/contacts.scss
> +  }
Брр...
Почему я так не люблю вложенность?
Потому что иногда к ней придется прибегнуть потому что без этого будет никак. И если в таком месте уже будет вложенность, то это не очень здорово.

2022-04-14 17:06 UTC, arturtrifonov commented on source/sass/blocks/form-input-font.scss
> +  font-family: "Open Sans", "Helvetica", sans-serif;
А еще можно написать вот так:
```suggestion
  font-family: inherit;
```

Тогда браузерные стили перепишет правило "наследуйся" и не нужно будет в разных местах прописывать полное семейство

2022-04-14 17:06 UTC, arturtrifonov commented on source/sass/blocks/field.scss
> +  line-height: 30px;
Все шрифтовые стили нужно писать в первую очередь самому инпуту. Шрифт инпута и шрифт плейсхолдера в 99% случаев различаются только интенсивностью цвета.
Если ты их пишешь плейсхолдеру, то может в итоге оказаться, что плейсхолдер имеет один стиль текста, а как начинаешь писать — вылезает совсем другой. Так почти никогда не бывает и не должно быть.

2022-04-14 17:06 UTC, wrgraff commented on source/sass/blocks/main-form/contest-form.scss
> +  margin-bottom: 26px;
> ну сейчас размеров у меня почти нигде нет, потому что пока непонятно, как их указывать (вернее понятно, что через медиа-выражения это надо будет делать и они будут меняться),

Медиа-выражения это больше про способ адаптива. Не все же стили будут только внутри них )
Вообще, чем меньше размеров будет указано — тем лучше. Желательно, чтобы блоки вписывались в сетку, описанную родителем.

> но про блоки я понимаю, что раз блок - самостоятельная единица, то его нельзя отступами ни к чему внешнему привязывать, так?

Да, получается что так =)

2022-04-14 17:07 UTC, wrgraff commented on source/sass/blocks/main-catalog/photo-card.scss
> +  margin-top: 27px;
Ну сделала то все правильно получается )
Можем на эту тему устроить консультацию

2022-04-14 17:15 UTC, wrgraff requested changes
Кажется, самую малость не хватило внимательности )

2022-04-14 17:15 UTC, wrgraff commented on source/form.html
> +            <label for="lastname-id" class="field__label form-label">Фамилия:</label>
Я вот не фанат вынесения шрифтовых стилей в такие отдельные точечные стили типа `form-label`. Так можно было бы далеко зайти и разбить все шрифты на отдельные стили, они довольно часто повторяются.

Но это на твое усмотрение. Попробуй пока так.

2022-04-14 17:15 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +.map-wrapper {
В файле `contacts.scss` не может быть класса `.map-wrapper`

2022-04-14 17:15 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  margin-top: 40px;
А еще у блока лучше не делать отступ. Может, его тут на селектор с элементом поменять просто?

2022-04-14 17:15 UTC, wrgraff commented on source/sass/blocks/nav-list.scss
> +  margin: 0;
Тут можно опять повториться про отступы у БЭМ-блоков )

2022-04-14 21:23 UTC, zazuzai commented on source/sass/blocks/main-catalog/photo-card.scss
> +  margin-top: 27px;
да, наверное стоит про это проговорить

2022-04-14 21:32 UTC, zazuzai commented on source/sass/common.scss
> +$font-color-accent: #d22856;
в итоге сделала и то и другое :-/

`ну добавят в серый голубой тон — все равно он серым будет` ужас какой. он же станет серо-голубой тогда!

2022-04-15 07:22 UTC, wrgraff approved these changes
👍

2022-04-15 07:22 UTC, merged