Адаптивная сетка для главной страницы
htmlacademy-adaptive/1853291-pink-25 pull request #6
Opened 2022-04-18 18:47 UTC by zazuzai

не ожидала, что буду настолько тупить и по несколько раз всё переделывать, чтобы понять что оно не работает :-/

- Не сделала таблицу с тарифами (которая слайдер)
- Меня терзают сомнения по поводу шрифтов. В инспекторе вроде Open Sans, но визуально это не он и будто нету light шрифта
- смутили переносы слов в макете, можно будет использовать <br>?  (а можно будет использовать его только для определённых состояний? о_О)

2022-04-19 19:51 UTC, wrgraff requested changes
А вот и наше первое видео-ревью =)
[Первая часть](https://youtu.be/bb611zVtV4I)
[Вторая часть](https://youtu.be/OEHm5VNHvyI)

PS: Понадобится время, чтобы в хорошем качестве загрузить

2022-04-19 19:51 UTC, arturtrifonov commented on source/index.html
> +      </div>
А куда делся `<nav>`?
Закрытый кусок тега при этом от него остался...

2022-04-19 19:51 UTC, arturtrifonov commented on source/index.html
> +        <p class="product-features__subtitle product-features__subtitle--1">
О нет, только не циферки в классах...
Нет никакого смысла использовать классы типа `something-1`, `something-2`, и так далее.

Если тебе нужно стилизовать что-то по порядковому номеру, то в CSS есть такие вещи, как `:first-child`, `:nth-child`, `:nth-of-type` и прочие. Они придуманы специально чтобы выбирать элемент по порядку. И если их в разметке перемешать, то они все равно будут выбирать по порядку.

Если же необходимо дать стили элементу так, чтобы при перемешивании стили оставались при нём (например, иконка, которая относится непосредственно к элементу), то нужен класс, отражающий суть этого изменения, а не порядковый номер.

2022-04-19 19:51 UTC, arturtrifonov commented on source/index.html
> +          <div class="contacts__item contacts__item--adress">
Ох уж это странное слово английское...
```suggestion
          <div class="contacts__item contacts__item--address">
```

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/nav-list.scss
> +  flex-direction: column;
Никогда не понимал, зачем студенты так любят ставить флекс, а потом превращать его в колонку, если можно ничего не делать и все элементы и так идут друг под другом... )

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/product-features.scss
> +    height: 382px;
Высоту можно задавать только элементам, для которых невозможно предположить переполнение.
Например — ссылка-иконка на соцсеть.
Список точно может измениться по высоте. Максимум, можно задать минимальную высоту. Но и то, такая высота приучает зачастую забывать об отступе снизу.

В общем, лучше вообще никакую высоту не использовать. Разве что она [реально нужна](https://mentorium.frontend-design.ru/articles/height-in-css/).

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/download-app.scss
> +  width: 280px;
Кажется здесь нужно центрирование

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/download-app.scss
> +}
Попробуй использовать грид для центрирования

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/header.scss
> +    padding-right: 130px;
Хэдер тоже должен отцентрироваться

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/nav-list.scss
> +  padding: 25px;
Эти отступы нужны ссылке

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/product-features.scss
> +
Нужно сделать текст внутри контентной области

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/product-features.scss
> +.product-features__wrapper {
Обертка тут почти бесполезна

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/product-features.scss
> +    height: 700px;
Резервировать место под картинки нужно паддингом

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/side-effect.scss
> +.side-effect {
Подумай о подходе с контейнером

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/side-effect.scss
> +    height: 430px;
Точно использовать отступы, возможно с минимальной высотой, но точно не просто высоту

2022-04-19 19:51 UTC, arturtrifonov commented on source/sass/blocks/contacts.scss
> +    order: 2;
Можно сделать работу order оптимальнее

2022-04-20 08:34 UTC, wrgraff commented
Про [box-sizing](https://frontend-design.notion.site/box-sizing-74c2b981a9624d03ba122967a529b9ad) ссылку забыл =)

2022-04-22 00:02 UTC, zazuzai commented
1) box-sizing на весь сайт - это здорово, но мне же вроде нельзя универсальные селекторы использовать

2)я услышала про wrapper и container, но пока не оформила

3)таблица продолжает меня уничтожать, теперь она не влезает номально в плашетную версию.
эм, стесняюсь спросить... может её попробовать сделать гридом?))

2022-04-22 13:44 UTC, wrgraff commented
1. Критерий [Д16](https://up.htmlacademy.ru/adaptive/25/criteries#d16) допускает использование некоторых глобальных стилей:
  ![изображение](https://user-images.githubusercontent.com/37917037/164726615-fc13c267-6731-4296-a9e1-cbd99c13cf56.png)
3. Не надо гридом

2022-04-23 08:42 UTC, wrgraff requested changes
Нууу, конечно еще не прям системность, но верстка работает правильно в плане размеров )
Нужно немного подправить ошибок, чтобы потом они нас не догнали. Думаю, это будет уже легко совсем

2022-04-23 08:42 UTC, wrgraff commented on source/form.html
> +        <button class="header__menu__toggle" type="button">
А что произошло с файлами кроме главной страницы? Тут какая-то другая разметка по сравнению с главной, что не есть хорошо.
А еще тут по БЭМ идет элемент элемента. Так быть не должно:
```suggestion
        <button class="header__toggle" type="button">
```

И для `header__menu__list` тоже надо править

2022-04-23 08:42 UTC, wrgraff commented on source/index.html
> +      <div class="header__nav container">
А почему не оставить это тегом `<nav>`?

2022-04-23 08:42 UTC, wrgraff commented on source/index.html
> +      <div class="header__nav container">
Проблема с контейнером для всего хэдера будет в том, что непонятно как ты будешь тянуть затем вот это меню от края до края (чтобы полоски пунктов меню тянулись на всю ширину):
<img width="676" alt="изображение" src="https://user-images.githubusercontent.com/37917037/164886317-49136cac-6415-45d8-94f5-2fd951f1183a.png">

То есть, именно для этого блока нужно по идее создать какую-то совсем свою сетку.

2022-04-23 08:42 UTC, wrgraff commented on source/index.html
> +            <p class="product-features__description product-features__description--last">
Элемент с модификатором `product-features__description--last` лучше выбирать через CSS.
Первый, последний, каждый второй, каждый третий в каждом ряду — все это можно и нужно выбирать через стили

2022-04-23 08:42 UTC, wrgraff commented on source/index.html
> +          <div class="contacts__item contacts__item--addressr">
```suggestion
          <div class="contacts__item contacts__item--address">
```

2022-04-23 08:42 UTC, wrgraff commented on source/index.html
> +      <section class="price container">
Хм, вроде разбирал как раз почему контейнер для таблицы обязательно нужен внутри. Эффект получается неправильный, к тебя таблица срезается по контентной области:
<img width="592" alt="изображение" src="https://user-images.githubusercontent.com/37917037/164886907-73824058-d695-4af5-9786-1a27cf771453.png">

Но она должна центрироваться и занимать ячейкой контентную область. А вот видно ее должно быть на всю ширину. Как раз поэтому может быть нужен внутри контейнер, а обрезка таблицы — по секшену.

2022-04-23 08:42 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +.contacts__item--addressr {
```suggestion
.contacts__item--address {
```

2022-04-23 08:42 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  @media (min-width: 320px) {
А зачем вообще медиа-запрос? Мобильная версия по сути с нуля работает и без медиа-запроса

2022-04-23 08:42 UTC, wrgraff commented on source/sass/style.scss
> +@import "./blocks/container.scss";
Ну все-таки первым из блоков надо поставить, не перед `common.scss`

2022-04-23 08:43 UTC, wrgraff commented
Таблицу оставь на декор.
Там по сути нужно возиться с мелочами

2022-04-24 06:49 UTC, zazuzai commented on source/index.html
> +      <div class="header__nav container">
задала фиксированнуу ширину блоку с лого и копкой меню, а у самого списка оставила авто, так можно?

2022-04-24 06:51 UTC, zazuzai commented on source/index.html
> +            <p class="product-features__description product-features__description--last">
ой
в стилях уже повесила нужное правило (убрать нижний отступ) на последний item, а из идекса модификатор  --last не убрала

2022-04-24 06:52 UTC, zazuzai commented on source/index.html
> +          <div class="contacts__item contacts__item--addressr">
o_O

2022-04-24 07:03 UTC, zazuzai commented on source/index.html
> +      <section class="price container">
Наверное я не понимаю какую-то важную вещь.(ничего не понимаю?)
 Вот сейчас overflow у меня на секции. Таблицу я завернула в div и задала ему flex и justify-content: center. Самой таблице я задала ширину 840px. Но она сжимается внутри контейнера. Аналогично с шириной ячеек. А если задать ширину контейнеру, то он не центрируется. 
 
 памагити

2022-04-24 08:21 UTC, wrgraff commented on source/index.html
> +      <section class="price container">
Эмм, вроде же все работает? )
Таблица не сжимается как-то, все нормально...

2022-04-24 08:22 UTC, wrgraff commented on source/index.html
> +      <div class="header__nav container">
Конечно

2022-04-24 08:25 UTC, wrgraff approved these changes
Не будем тормозиться на нюансы с таблицей. Если что — вместе сядем и допилим

2022-04-24 08:25 UTC, wrgraff commented on source/sass/blocks/intro.scss
> +/* .intro {
Лучше конечно за комментированный код в ПР не отправлять

2022-04-24 08:25 UTC, merged