Адаптивная сетка внутренних страниц
htmlacademy-adaptive/1853291-pink-25 pull request #7
Opened 2022-04-25 17:58 UTC by zazuzai

2022-04-26 16:50 UTC, wrgraff requested changes
**Есть некоторые проблемы в работе хэдера.** — 🚀
Он должен быть на десктопе ограничен по ширине контента. А он до него не дотягивает:
![изображение](https://user-images.githubusercontent.com/37917037/165347008-0f3f3d02-e50d-44e2-9b4f-6758c00665c9.png)

У тебя там довольно сложная конструкция с шириной для `.header__menu`. Он ставится 280, потом только для планшета ставится другой размер. Из-за этого на десктопе опять 280. Это не совсем удобно и не совсем верно. Пока лучше действовать проще. На десктопе должен сжаться этот блок. Ну или получить размер строго под лого. А ширину через `.header__nav` ограничить надо.

**И есть проблема с футером** — 🚀
Но тут проще. На главной он центрируется, а на странице конкурса — нет.

В целом уже сильно лучше выходит, набиваешь руку!
Еще чуть-чуть и выдадим тебе звание "Мастер сеток" ))

2022-04-26 16:50 UTC, wrgraff commented on source/sass/blocks/photo-card.scss
> +.photo-card--special {
Надо еще как-то придумать, как именно эта картинка должна на всю ширину страницы растягиваться.
Это сложно, но это один из главных челленджей этого проекта

2022-04-26 16:50 UTC, arturtrifonov commented on source/sass/blocks/upload-photo.scss
> +    width: 940px;
Ширину блокам лучше не задавать, помнишь? Я бы подумал вообще о том, чтобы переместить именно фон с внешней обертки на внутреннюю, а центрирование всегда ставить внутри

2022-04-26 16:50 UTC, arturtrifonov commented on source/sass/blocks/intro.scss
> +.intro__title--catalog {
Вот тут как раз хороший пример того, где минимальная высота прям именно тот инструмент, который решает задачу, поставленную макетом.
Минимум высота под 3 строки. Если больше — элемент вырастет. Если 2 строки — пустота сама сформируется снизу:
![изображение](https://user-images.githubusercontent.com/37917037/165351197-475fa5ac-0027-4713-a381-d594de934e4a.png)

2022-04-26 16:50 UTC, wrgraff commented on source/sass/blocks/contest-form.scss
> +.contest-form__group:nth-child(2) {
Не уверен, что тут хороша выборка по порядку. Ведь мало ли какой модуль с каким контентом добавят потом.
Я бы, кстати, использовал grid-area здесь, потому что порядком сложно перестраивать, а с area получится прям наглядно написать в коде что и где должно быть.

2022-04-26 16:50 UTC, wrgraff commented on source/form.html
> -        <div class="contest-form__group field">
Молодец, здесь очень логично перестроить разметку под десктоп, потому что именно там идет управление табом!

2022-04-26 16:50 UTC, arturtrifonov commented on source/sass/blocks/container.scss
> +.container--half {
Чет странное )
Из названия вот не очень очевидно, что это половина именно на десктопе будет

2022-04-28 21:16 UTC, zazuzai commented on source/sass/blocks/upload-photo.scss
> +    width: 940px;
цвет фона тут на форме и он должен тянуться на мобильной и планшетной версии, а на декстопе обрезается, поэтому задала там ширину

2022-04-29 07:29 UTC, wrgraff commented on source/sass/blocks/upload-photo.scss
> +    width: 940px;
Это я понимаю )
Есть еще альтернативная версия реализации:
- блок всегда тянется
- контейнер всегда центрирует (пускай он и есть форма)
- на мелких экранах фон на самом блоке
- на крупном экране фон убирается с блока и добавляется на контейнере

Плюс в том, что "геометрию" элементов мы так не меняем. Она все-таки чуть больше влияет на всё вокруг и внутри. Ну и в принципе перестроения сетки всегда требуют больше внимания, а фон переключить — это так, мелочи

2022-04-29 08:11 UTC, wrgraff requested changes

2022-04-29 08:11 UTC, arturtrifonov commented on source/sass/blocks/contest-form.scss
> +    flex-direction: column;
Но ведь все сломалось (
Кажется, ты запуталась слегка с grid areas. Я тебе [пояснялку](https://youtu.be/zCxX54lYNFQ) записал. Прикрепляю сразу же после начала загрузки, так что смотри: на момент публикации ревью возможно придется подождать публикации в хорошем качестве (там 20 минут, это относительно шусто должен ютуб сделать)

2022-04-29 08:11 UTC, arturtrifonov commented on source/sass/blocks/container.scss
> +.container--desktop {
Все равно не очень логично.
Вообще, дополнительную логику в общий класс `container` может и не стоит помещать...

2022-04-29 08:11 UTC, arturtrifonov commented on source/sass/blocks/photo-card.scss
> +  max-width: 320px;
Вроде бы там логика как раз в том, что картинка упираться должна...
Чтобы она нормально тянулась, не искажаясь в пропорциях, используй для нее `object-fit: cover`. Он помогает [управлять тем, как картинка заполняет пространство](https://doka.guide/css/object-fit/).

2022-05-02 07:26 UTC, zazuzai commented on source/sass/blocks/contest-form.scss
> +    flex-direction: column;
вернулась к тому, что понимаю - к конструкции и флекса, ордера и палок (и класса контейнер)

2022-05-02 08:07 UTC, wrgraff approved these changes

2022-05-02 08:07 UTC, wrgraff commented on source/sass/blocks/contest-form.scss
> +  justify-content: center;
🤔

2022-05-02 08:07 UTC, merged