Декоративные элементы главной страницы
htmlacademy-adaptive/1853291-pink-25 pull request #8
Opened 2022-05-03 22:54 UTC by zazuzai

2022-05-04 19:09 UTC, wrgraff requested changes
Ну, начинает вырисовываться сайт, вполне даже похож местами.
Но где же все фоновые картинки? =(

2022-05-04 19:09 UTC, arturtrifonov commented on Readme.md
> +<img width="800" alt=" " src="https://user-images.githubusercontent.com/10909/60808088-259e3a80-a190-11e9-98f7-3c0edd9740f5.jpg">
Эээ, что это? =)

2022-05-04 19:09 UTC, arturtrifonov commented on source/img/price-table/popular-tablet.svg
> +</svg>
В принципе, эти лейблы "хит" можно вообще сделать через CSS

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/button-primary.scss
> +    font-size: 21px;
В макете высота строки остается 18. Фактически же так делать не стоит.
Лучше проигнорировать макет, поставить нормальную высоту строки и подогнать отступами кнопку под тот размер, которого она должна быть

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/button-primary.scss
> +  justify-content: center;
Не понял я как-то в чем прикол делать кнопку флексом и центровать в ней текст через флекс О_О

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/button-primary.scss
> +  width: 100%;
Ширину БЭМ-блокам мы все-таки задаем?

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/contacts.scss
> +  color: #bfc3c7;
Не очень здорово, что так много цветов в итоге заданы напрямую. Переменные по сути не используются в полную силу

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/copyright.scss
> +  svg path {
Такая конструкция дает 3 уровня вложенности: `.copyright__link` > `svg` > `path`.
Это запрещено критерием.

Рекомендую пока не заморачиваться с цветами в svg. Когда будем делать svg-спрайт напомни, чтобы мы с тобой разобрали `currentColor`.
Пока просто удали вложенность, а если не будет почему-то меняться цвет — то и ладно, доберемся на спрайтах до этого.

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/download-app.scss
> +  background-color: #1d2631;
Вроде бы переменная была, а теперь ее нет... (

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/footer.scss
> +  svg path {
Тут тоже 3 уровня вложенности

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/header.scss
> +  background-color: rgba(0, 0, 0, 0.3);
Даже в таком случае можно использовать переменную. В этом как раз преимущество препроцессора, он ее "развернет" в нужный формат:
```suggestion
  background-color: rgba($color-black, 0.3);
```

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/header.scss
> +  position: relative;
А зачем relative?

Кстати, раз зашла речь о позиционировании. Нужно сделать так, чтобы навигация накрывала блок с картинкой, а не была перед ним.
Здесь допустимо абсолютное позиционирование использовать. Ну, или придумать что-нибудь похитрее, чтобы переполнение работало. Но это по желанию

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/header.scss
> +}
Тройная вложенность получается и тут тоже.
Кстати, интересно, почему именно так сформирована вложенность...
А например не так )
```suggestion
.header__logo:hover svg path {
  fill: $color-accent;
}
```

Или так!
```suggestion
.header__logo {
  &:hover svg path {
    fill: $color-accent;
  }
}
```

Но это уже так, баловство. Главное конечно количество уровней вложенности

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/header.scss
> +.header__nav--closed .nav-list {
`nav-list` не может стилизоваться от модификатора элемента другого блока (`header`).
Это прямо нарушает и критерий и основной принцип БЭМ — независимость блоков

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/header.scss
> +  content: " ";
А зачем же в контент поставлен пробел?

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/header.scss
> +}
Есть такой принцип при написании кода: DRY (don't repeat yourself).
Мы конечно можем им даже где-то пренебрегать (ради той же пресловутой независимости БЭМа — но методология важнее), но в основном стараемся следовать.
Здесь у тебя очень много одинакового кода. Можно его сократить, чтобы не писать по 2 раза одно и тоже:
```suggestion
.header__nav--opened .header__toggle::before,
.header__nav--opened .header__toggle::after {
  content: "";
  position: absolute;
  right: 0;
  width: 33px;
  height: 3px;
  transform: rotate(45deg);
  background-color: #ffffff;
}

.header__nav--opened .header__toggle::after {
  transform: rotate(-45deg);
}
```

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/header.scss
> +}
Да, заметь, я еще и `display: block;` грохнул.
Это потому что при абсолютном позиционировании любой элемент по поведению будет блочным боксом.

Бонусный вопрос:
Есть как минимум еще 2 случая, когда `display: block;` не будет играть никакой роли. Сможешь сказать какие?

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/nav-list.scss
> +  box-shadow: 0 1px 0 #000000, inset 0 1px 0 rgba(255, 255, 255, 0.15);
Так это получается у тебя одну темную полосу рисует тень, а другую рамка. Надо как-то определиться с подходом, а то они задваиваются

2022-05-04 19:09 UTC, arturtrifonov commented on source/sass/blocks/nav-list.scss
> +  border-bottom: 1px solid #000000;
А тут еще третья полоска )

2022-05-04 19:09 UTC, wrgraff commented on source/sass/blocks/price-table.scss
> +  border-right: 2px solid $color-gray;
Получается не очень по макету. У меня есть [плейлист из коротких роликов](https://youtube.com/playlist?list=PL6xpnt2woRKm3kTayObm0L_8COGsEK1UL), где поэтапно раскрывается как можно более-менее симпатично все эти скругления реализовать.
Я его даю тем, кто уже помучался немного сам. Посмотри и ты теперь )

2022-05-07 15:14 UTC, zazuzai commented on source/sass/blocks/download-app.scss
> +  background-color: #1d2631;
это другой цвет и он только в этом блоке

2022-05-07 15:27 UTC, zazuzai commented on source/sass/blocks/header.scss
> +  position: relative;
Вроде сделяль. Но я сдаюсь бороться (страдать) с этой картинкой на фоне секции про скачивание, которая должна лежать и на хэрере тоже.
Положить весь этот кусок в хэдер? 
+ картинка с рукой - я помню про то, что можно задать два разных фона через background, но у меня не получилось задать им разные размеры + задать фоновый цвет, который тоже должен тянуться на всю ширину. - чделать через before?

2022-05-07 15:28 UTC, zazuzai commented on source/sass/blocks/header.scss
> +}
эм, для тех элементов, которые по умолчанию отобраются как блоки? (div, p)?

2022-05-07 15:42 UTC, zazuzai commented on source/sass/blocks/nav-list.scss
> +  box-shadow: 0 1px 0 #000000, inset 0 1px 0 rgba(255, 255, 255, 0.15);
я так сделала, чтобы задать бордеры только списку, без границы у верхней секции с меню. сейчас оставила тень, но убрала у неё первое значение, вроде не задваивается

2022-05-07 15:43 UTC, zazuzai commented on source/sass/blocks/price-table.scss
> +  border-right: 2px solid $color-gray;
посмотрела

божечки-кошечки

2022-05-08 08:39 UTC, wrgraff commented on source/sass/blocks/copyright.scss
> +.copyright__link:hover svg path {
Эээ... Но тройной уровень вложенности остался же. Вопрос про способ оформления был дополнительным. А про вложенность — основной. Потому что нарушает [критерий Д10](https://up.htmlacademy.ru/adaptive/25/criteries#d10) (здесь и в других таких же случаях со стилизацией svg)

2022-05-08 08:39 UTC, wrgraff commented on source/sass/blocks/download-app.scss
> +  background-color: #1d2631;
Дело в том, что переменные тем больше помогают, чем более "абсолютно" ты их используешь.
Вот в чем вообще их польза?
1. Если поменять значение в одном месте, то оно поменяется везде;
2. Позволяют упорядочить и контролировать применение цветов. 

Цели 1 мы отчасти добиваемся, Если цвет используется только один раз. Тут конечно есть вопрос тоже: мы делаем 3 страницы сайта — какова вероятность, что этот цвет встретится на других страницах?

Но вторая задача не решается совсем:
- если через 3 месяца нужно внести правки, где нужно будет добавить этот цвет — вспомнишь ли ты, что он уже используется, но без переменной?
- если у нас в оформлении 3 оттенка темно-синих и дизайнер сказал, что надо поменять темно-синий цвет, какая вероятность, что поменяется все 3? Довольно высока, так как обычно это один цвет и его производные
- бывает и такое, что в макете используются очень близкие цвета, и составив из них палитру мы в итоге можем посоветоваться с дизайнером и отбросить лишнее (хотя он сам должен с палитры начинать вообще-то)

При чем, по моему опыту могу сказать, что цвета сайта меняются довольно редко и намного больше пользы приносит именно упорядочивание и такой "системный" подход к цветам.

Вот например мой набор переменных из сайта котов:
![изображение](https://user-images.githubusercontent.com/37917037/167288370-64fdf3e4-3863-4ada-a62a-3a95b6f81fa3.png)
Вышло не очень ровно, пришлось впаять какой-то странный 180-й серый =)
Но сказать по правде, я один еще и выкинул. Там был цвет вообще с микроскопическим сдвигом. И вот наверняка никто не заметит даже.

2022-05-08 08:50 UTC, wrgraff commented on source/sass/blocks/header.scss
> +}
Тогда это было бы 322 случая, или сколько там этих элементов с блочным боксом по умолчанию )

Вопрос то к другому. `position: absolute` создает блочный бокс из элемента, какой бы `display` у него не был прописан. Есть еще 2 случая, когда это свойство будет проигнорировано.

<details>
<summary>Ответ тут</summary>

Суть в том, что если у родителя задан флекс или грид, то все потомки становятся флекс-элемментами или грид-элементами соответственно. Они будут игнорировать значение свойства `display`, даже если ты туда пропишешь `inline`.
При этом важный момент: все это касается того, как свойство определяет внешнее поведение блока. Ведь свойство `display` отвечает и за поведение снаружи, и за поведение потомков внутри (тот же грид больше меняет внутреннюю структуру, внешне он создает обычный блочный бокс).

</details>

2022-05-08 08:52 UTC, wrgraff commented on source/sass/blocks/price-table.scss
> +  border-right: 2px solid $color-gray;
Зато красиво )

2022-05-08 22:06 UTC, zazuzai commented on source/sass/blocks/header.scss
> +}
😯

2022-05-09 12:08 UTC, wrgraff approved these changes

2022-05-09 12:08 UTC, wrgraff commented on source/index.html
> +          </button>
Кнопки эти я бы разместил лучше не в айтеме, а снаружи. Вообще, стоит иметь ввиду, что тут в разметке должно быть 3 отзыва (судя по кнопочкам под ними).

И кнопки размещал бы рядом. Логично, если порядок будет такой, что у нас идет навигация назад, навигация вперед, а потом контент. Ну или сначала контент, но логично когда доступ к кнопкам рядом

2022-05-09 12:08 UTC, merged