Декоративные элементы внутренних страниц
htmlacademy-adaptive/1853291-pink-25 pull request #9
Opened 2022-05-11 22:32 UTC by zazuzai

2022-05-11 22:39 UTC, zazuzai commented
не получилось совсем:
1) секция с оработкой загружаемой фотографии на странице каталога, там хитро должен показываться один range-bar и в "неактивном" режиме кнопки от других фильтров. не понимаю, надо ли это сделать просто визуально или чтобы оно работало (как-то через доволнительные инпуты, чтобы фильтры можно было переключать)

2)опять в каталоге, но уже высота карточек. я понимаю, что надо как-то растянуть среднюю часть карточки, где идёт описание фото, но у меня не поулчилось

2022-05-13 08:21 UTC, arturtrifonov commented on source/form.html
> +                  <input class="radio__input visually-hidden" type="radio" name="platform" value="iOS" checked>
Не спеши скрывать чекбоксы через `visually-hidden`. Это не самый оптимальный и лучший способ скрытия для доступности. У Сары Суайдан есть [целая статья про способы прятать чекбоксы доступно](https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/), и там это подробно разобрано.

Статья большая и на английском, поэтому, если тебе не хочется / некогда / сложно ее читать, вот основная идея:

> Есть для незрячих такой способ взаимодействия с интерфейсом: водить пальцем по экрану и слушать что под пальцем находится. При таком сценарии пользователь около лейбла будет ожидать увидеть чекбокс. Так что гораздо лучше, если он не будет скрыт, а будет там реально находиться.
> 
> Как это сделать:
> 1. убрать чекбокс из потока с помощью `position: absolute`;
> 2. расположить его поверх изображения, которое визуально изображает чекбокс;
> 3. установить его размеры, чтобы они соответствовали размеру изображения;
> 4. визуально скрыть чекбокс с помощью `opacity: 0`.
> 
> https://user-images.githubusercontent.com/37917037/128550004-fb60ed66-cd1c-4bd4-8d31-2771be5d09b0.mp4

2022-05-13 08:21 UTC, arturtrifonov commented on source/form.html
> +                  <span class="radio__box"></span>
Придирчивый наставник может на защите докопаться до этих боксов по критерию [Д2](https://up.htmlacademy.ru/adaptive/25/criteries#d2), так как оформить чекбоксы можно и без них.
На первом уровне вашего потока почему-то вдруг решили делать вот так — через отдельный элемент, хотя раньше показывали как обходиться без него.

Я записал [плейлист](https://youtube.com/playlist?list=PL6xpnt2woRKlunJxlAzDXJxhwp9HGJxEk) вообще про странности в том проекте Барбершопа и то, как можно сделать это альтернативными методами.
Вторая часть там как раз про чекбоксы. Она из первого уровня, но между первым и вторым ничего особо не меняется в этом плане.

2022-05-13 08:21 UTC, arturtrifonov commented on source/form.html
> +        </div>
Что-то пошло не так с вложенностью тегов )

2022-05-13 08:21 UTC, arturtrifonov commented on source/catalog.html
>                  <button class="editing-tools__button editing-tools__button--crop">
Кнопкам обязательно нужно поставить атрибут `type`.
Сейчас они отправляют форму (все 3 кнопки)

2022-05-13 08:21 UTC, wrgraff commented on source/catalog.html
> +                <div class="editing-tools__range editing-tools__range--crop range-bar">
По поводу твоего вопроса об этих кнопках.
Они по своей сути работают как вкладки. Жмешь кнопку и появляется соответствующий ей ползунок. При этом сама кнопка становится активной (это кстати повод для того, чтобы поместить svg в кнопку, так как он должен уметь перекрашиваться).

Подсказываю: гораздо удобнее кнопки расположить вместе: сперва список кнопок, потом — список инпутов. Кнопки всегда видны, а инпуты будут переключаться каким-нибудь там модификатором `blablabla--active`.
Реализовывать механизм переключения не нужно, нам нужно только оформление.

Тут ты можешь возразить, что начиная с планшета позиционировать 2 списка будет неудобно и вообще неправильно:
![Снимок экрана 2022-05-13 в 11 04 10](https://user-images.githubusercontent.com/37917037/168239107-4b81ff2f-37b8-40fe-a5e2-154e9d92c685.png)

И в общем-то это правда. Но!
Давай подумаем: а нужны ли кнопки в этом формате? Кнопки переключают активный инпут на экране, где инпут только один. А у нас их — все 3. Будет ли польза от кнопок в таком случае? На самом деле, от них будет только вред: это интерактивные элементы, которые ничего не делают. Они будут попадать в фокус и скринридеры и путать пользователя.
Поэтому, хорошим решением будет спрятать с этого момента список кнопок, а эти иконки сделать частью оформления самих инпутов (в лейбле или общей обертке — от верстки зависит)

2022-05-13 08:21 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +  background-image: url("../img/form/Mobile/tick.svg");
Ой-ой, не должно быть регистра с заглавными в папках и файлах!

background-image: url("../img/form/`Mobile`/tick.svg");

Вообще как-то сложно. Тем более, это svg, зачем ей мобильная папка, она же масштабируется свободно.

2022-05-13 08:21 UTC, wrgraff commented on source/sass/blocks/editing-tools.scss
> +
Двойной отступ — ошибка форматирования кода

2022-05-13 08:21 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +  box-shadow: 0, 7px, 15px 0, #00010126;
Параметры тени без запятых пишутся. Через запятую можно вторую тень прописать (как с фоном)
```suggestion
  box-shadow: 0 7px 15px 0 #00010126;
```

2022-05-13 08:21 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +  box-shadow: 0, 7px, 15px 0, #00010126;
А кстати, ты знаешь почему у цвета так много символов в этом формате?

box-shadow: 0 7px 15px 0 `#00010126`;

2022-05-13 08:21 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +  top: 30%;
Обычно все-таки модалки ставят строго по центру. Ну или не строго, но 30% — это не очень надежно. А вдруг у меня очень невысокий монитор?

2022-05-13 08:29 UTC, wrgraff requested changes
Для решения задачи с карточкой товара тебе нужно воспользоваться гридами или вертикальным флексом (второе наверное удобнее будет, так как нет жесткой привязки к количеству рядов).
Там есть возможность через `flex-grow` растягивать элементы на все пустое пространство. Или отталкивать их друг от друга через `margin: auto`. 

Пробовала такие подходы? )

2022-05-13 08:29 UTC, wrgraff commented on source/form.html
>      <div class="modal modal--success modal--close">
У модалок даже есть заголовок второго уровня, который чаще всего замечательно озаглавливает какой-нибудь `<section>`. А почему бы и модалке не быть секшеном? По всем параметрам подходит: блок информации с законченным смыслом и даже уже озаглавленный

2022-05-13 08:29 UTC, wrgraff commented on source/sass/blocks/range-bar.scss
> +input[type="range"] {
Здесь и далее идут селектору по инпуту, что запрещено критерием [Д16](https://up.htmlacademy.ru/adaptive/25/criteries#d16)

2022-05-13 08:29 UTC, wrgraff commented on source/sass/blocks/range-bar.scss
> +input[type="range"]::-webkit-slider-runnable-track {
Кроме того, такой селектор противоречит и правилам БЭМа, которые касаются структуры файлов.
То есть, этот селектор не соответствует блоку `range-bar` и нарушает [Б13](https://up.htmlacademy.ru/adaptive/25/criteries#b13)

2022-05-13 20:01 UTC, zazuzai commented on source/form.html
> +                  <input class="radio__input visually-hidden" type="radio" name="platform" value="iOS" checked>
😮
сделала
только чтобы поставить их совсем выше изображения пришлось использовать z-index, это ок?

2022-05-13 20:19 UTC, zazuzai commented on source/sass/blocks/modal.scss
> +  box-shadow: 0, 7px, 15px 0, #00010126;
*вздыхает и идёт гуглить

2022-05-13 20:25 UTC, zazuzai commented on source/sass/blocks/range-bar.scss
> +input[type="range"]::-webkit-slider-runnable-track {
☹️ когда рано порадовалась, что нашла как застилизовать эти инпуты ☹️

2022-05-13 21:04 UTC, zazuzai commented
> Для решения задачи с карточкой товара тебе нужно воспользоваться гридами или вертикальным флексом (второе наверное удобнее будет, так как нет жесткой привязки к количеству рядов). Там есть возможность через `flex-grow` растягивать элементы на все пустое пространство. Или отталкивать их друг от друга через `margin: auto`.
> 
> Пробовала такие подходы? )

пробовала c гридами, но не получилось. про flex-grow забыла :(

2022-05-14 19:33 UTC, wrgraff commented on source/catalog.html
> +                  <svg class="editing-controls__icon" width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
```suggestion
                  <svg class="editing-controls__icon" width="44" height="44" viewBox="0 0 44 44" fill="none">
```

Можно удалить `xmlns="http://www.w3.org/2000/svg"`, он нужен только в файле, так браузер распознает формат файла. А когда встраиваешь код, то браузер и так распознает формат svg =)

2022-05-14 19:33 UTC, wrgraff commented on source/catalog.html
> +                  <svg class="editing-controls__icon" width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
```suggestion
                  <svg class="editing-controls__icon" width="44" height="44" viewBox="0 0 44 44" fill="none" aria-hidden="true">
```

А еще можно добавить `aria-hidden="true"`. Чисто на всякий случай, чтобы ничего лишнего не прочиталось кроме специального добавленного текста

2022-05-14 19:33 UTC, wrgraff commented on source/catalog.html
> +                    </g>
Лучше убрать прозрачность из кода иконки и добавить ей прозрачность через CSS.
А то сложновато переключать будет состояние модификатором ))
```html
<g opacity="0.3">
  ...
</g>
```

2022-05-14 19:33 UTC, wrgraff commented on source/catalog.html
> +                  <input class="range-bar__input range-bar__input--not-active" type="range" name="contrast-input" id="contrast-input-id">
А зачем тебе модификатор и на инпуте, и на айтеме?

2022-05-14 19:33 UTC, wrgraff commented on source/form.html
>          </div>
А с вложенностью тегов все еще что-то не так

2022-05-14 19:33 UTC, wrgraff commented on source/form.html
> +                  <input class="radio__input visually-hidden" type="radio" name="platform" value="iOS" checked>
Да, это ок )

2022-05-14 19:34 UTC, wrgraff commented on source/form.html
> +        </div>
Все еще осталась проблема с форматированием:
![изображение](https://user-images.githubusercontent.com/37917037/168445932-debc3f32-6eb5-4bb5-aa3f-8895db107a7e.png)

2022-05-14 19:35 UTC, wrgraff commented on source/form.html
> +        </div>
Должно быть так )
![изображение](https://user-images.githubusercontent.com/37917037/168445961-a17ef8ad-e761-4184-833f-8ecdc4543fc8.png)

2022-05-14 19:42 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +  top: 50%;
Это не в центре получится окно, а только верх окошка в центре.
Вообще, так как у тебя белое окно это не сама модалка, а `.modal__container`, то можно сделать такой пассаж:

```scss
  top: 0;
  display: grid;
  place-content: center;
```

2022-05-14 19:42 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +  box-shadow: 0, 7px, 15px 0, #00010126;
Нагуглила? )

2022-05-14 19:43 UTC, wrgraff commented on source/sass/blocks/range-bar.scss
> +input[type="range"]::-webkit-slider-runnable-track {
Не, стилизовала то нормально, только селекторы надо переделать с варианта по тегу на вариант по классам

2022-05-14 19:44 UTC, wrgraff approved these changes

2022-05-14 19:44 UTC, merged